DROP SCHEMA IF EXISTS SPRING;
CREATE SCHEMA SPRING;

DROP TABLE IF EXISTS SPRING.APP_USER;
DROP TABLE IF EXISTS SPRING.AUTHORITY;
DROP TABLE IF EXISTS SPRING.PRODUCT;

CREATE TABLE SPRING.APP_USER (
     id IDENTITY PRIMARY KEY,
     username VARCHAR(45) NOT NULL,
     password VARCHAR(450) NOT NULL,
     algorithm VARCHAR(45) NOT NULL
);

CREATE TABLE SPRING.AUTHORITY (
     id IDENTITY PRIMARY KEY,
     name VARCHAR(45) NOT NULL,
     app_user_id bigint NOT NULL
);

alter table SPRING.AUTHORITY
  add foreign key(app_user_id) references SPRING.APP_USER(id);

CREATE TABLE SPRING.PRODUCT (
     id IDENTITY PRIMARY KEY,
     name VARCHAR(45) NOT NULL,
     price VARCHAR(45) NOT NULL,
     currency VARCHAR(45) NOT NULL
);
