
DROP TABLE IF EXISTS APP_USER;
DROP TABLE IF EXISTS OTP;

CREATE TABLE APP_USER (
 username VARCHAR(45) PRIMARY KEY,
 password VARCHAR(250) NOT NULL
);

CREATE TABLE  OTP (
 username VARCHAR(45) PRIMARY KEY,
 code VARCHAR(45) NOT NULL
);
