#spring.thymeleaf.cache=false
spring:
  datasource:
    generate-unique-name: false
    name: spring
    url: jdbc:h2:mem:spring
    username: sa
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always




