#spring.thymeleaf.cache=false
spring:
  datasource:
    generate-unique-name: false
    name: spring
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  #
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true




